apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  template:
    metadata:
      labels:
        io.kompose.service: api
    spec:
      containers:
        - env:
            - name: RDS_DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: RDS_DB_NAME
                  name: sbmysql-app-config
            - name: RDS_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  key: RDS_HOSTNAME
                  name: sbmysql-app-config
            - name: RDS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: RDS_PASSWORD
                  name: sbmysql-app-secrets
            - name: RDS_PORT
              valueFrom:
                configMapKeyRef:
                  key: RDS_PORT
                  name: sbmysql-app-config
            - name: RDS_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: RDS_USERNAME
                  name: sbmysql-app-config
          image: atmakurikirankumar/sbmysql-docker-example
          imagePullPolicy: ""
          name: api
          ports:
            - containerPort: 8080
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
